image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

compile:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

verify:
  stage: test
  script:
    - mvn verify